openapi: 3.0.3
info:
  title: Better Auth Service API
  description: Authentication service for Fubuni Chat application
  version: 1.0.0
  contact:
    name: Fubuni Team

servers:
  - url: http://localhost:4000
    description: Development server
  - url: https://auth-service.hf.space
    description: Production server (Hugging Face Spaces)

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: auth-service

  /api/auth/sign-up/email:
    post:
      summary: Register new user with email and password
      operationId: signUpEmail
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
        '400':
          description: Invalid input (email format, password too short)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/sign-in/email:
    post:
      summary: Sign in with email and password
      operationId: signInEmail
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Sign in successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/sign-in/social:
    post:
      summary: Initiate social sign-in (redirects to provider)
      operationId: signInSocial
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - provider
              properties:
                provider:
                  type: string
                  enum: [google]
                  description: OAuth provider
                callbackURL:
                  type: string
                  description: URL to redirect after OAuth
      responses:
        '302':
          description: Redirect to OAuth provider
          headers:
            Location:
              description: OAuth provider URL
              schema:
                type: string

  /api/auth/callback/google:
    get:
      summary: Google OAuth callback
      operationId: googleCallback
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
          description: Authorization code from Google
        - name: state
          in: query
          schema:
            type: string
          description: State parameter for CSRF protection
      responses:
        '302':
          description: Redirect to application with session
          headers:
            Location:
              description: Application URL
              schema:
                type: string
            Set-Cookie:
              description: Session cookie
              schema:
                type: string

  /api/auth/session:
    get:
      summary: Get current session
      operationId: getSession
      tags:
        - Session
      security:
        - cookieAuth: []
        - bearerAuth: []
      responses:
        '200':
          description: Session retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/sign-out:
    post:
      summary: Sign out and invalidate session
      operationId: signOut
      tags:
        - Authentication
      security:
        - cookieAuth: []
        - bearerAuth: []
      responses:
        '200':
          description: Signed out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
          headers:
            Set-Cookie:
              description: Clear session cookie
              schema:
                type: string

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: better-auth.session_token
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    SignUpRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          example: securepassword123
        name:
          type: string
          example: John Doe

    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: securepassword123

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        session:
          $ref: '#/components/schemas/Session'

    SessionResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        session:
          $ref: '#/components/schemas/Session'

    User:
      type: object
      properties:
        id:
          type: string
          example: usr_abc123
        email:
          type: string
          example: user@example.com
        name:
          type: string
          example: John Doe
        emailVerified:
          type: boolean
          example: false
        image:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Session:
      type: object
      properties:
        id:
          type: string
        token:
          type: string
        userId:
          type: string
        expiresAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              example: Invalid credentials
            code:
              type: string
              example: INVALID_CREDENTIALS
