openapi: 3.0.3
info:
  title: Fubuni Auth API
  description: Authentication endpoints for Fubuni Chat
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://maryanrar-fubuni-chat-api.hf.space
    description: Production server

paths:
  /api/auth/register:
    post:
      summary: Register new user
      description: Create a new user account with email and password
      operationId: register
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Validation error (invalid email, weak password)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/login:
    post:
      summary: Login with email/password
      description: Authenticate user and return JWT tokens
      operationId: login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many failed attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/refresh:
    post:
      summary: Refresh access token
      description: Exchange refresh token for new access token
      operationId: refresh
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/logout:
    post:
      summary: Logout user
      description: Revoke refresh token
      operationId: logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/me:
    get:
      summary: Get current user
      description: Return authenticated user's profile
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/google:
    get:
      summary: Initiate Google OAuth
      description: Redirect to Google authentication page
      operationId: googleLogin
      tags:
        - Authentication
      responses:
        '302':
          description: Redirect to Google

  /api/auth/google/callback:
    get:
      summary: Google OAuth callback
      description: Handle Google authentication callback
      operationId: googleCallback
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to frontend with tokens

  /.well-known/jwks.json:
    get:
      summary: Get JWKS
      description: Return JSON Web Key Set for token verification
      operationId: getJwks
      tags:
        - Authentication
      responses:
        '200':
          description: JWKS response
          headers:
            Cache-Control:
              schema:
                type: string
                example: public, max-age=3600
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwksResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          example: securepassword123
        name:
          type: string
          example: John Doe

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: securepassword123

    RefreshRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          example: eyJhbGciOiJSUzI1NiIs...

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJSUzI1NiIs...
        refresh_token:
          type: string
          example: eyJhbGciOiJSUzI1NiIs...
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          description: Access token expiry in seconds
          example: 900

    UserResponse:
      type: object
      properties:
        id:
          type: string
          example: user-uuid-123
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          nullable: true
          example: John Doe
        image:
          type: string
          nullable: true
          example: https://example.com/avatar.jpg
        email_verified:
          type: boolean
          example: false

    JwksResponse:
      type: object
      properties:
        keys:
          type: array
          items:
            type: object
            properties:
              kty:
                type: string
                example: RSA
              kid:
                type: string
                example: fubuni-auth-key-1
              n:
                type: string
                description: RSA modulus (base64url)
              e:
                type: string
                example: AQAB
              alg:
                type: string
                example: RS256
              use:
                type: string
                example: sig

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: Invalid credentials
        code:
          type: string
          example: INVALID_CREDENTIALS
