"""
Authentication middleware for validating JWT tokens from the auth-service.
Uses JWT validation instead of calling auth-service for each request.
"""

from typing import Optional
from dataclasses import dataclass
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import jwt as pyjwt
from ..config.settings import settings


# HTTP Bearer token scheme
security = HTTPBearer(auto_error=False)


@dataclass
class AuthUser:
    """Authenticated user data from JWT token."""
    id: str
    email: str
    name: Optional[str] = None
    image: Optional[str] = None
    email_verified: bool = False


async def verify_token(token: str) -> Optional[AuthUser]:
    """
    Verify the JWT token using the shared secret.

    The token is generated by the auth-service and contains user information.
    """
    try:
        print(f"Verifying JWT token: {token[:20]}..." if token else "No token provided")

        # Verify and decode the JWT token
        payload = pyjwt.decode(
            token,
            settings.jwt_secret,
            algorithms=["HS256"]
        )

        print(f"Token verified successfully. Payload: {payload}")

        return AuthUser(
            id=payload["userId"],
            email=payload["email"],
            name=payload.get("name"),
            email_verified=payload.get("emailVerified", False),
        )

    except pyjwt.ExpiredSignatureError:
        print("Token has expired")
        return None
    except pyjwt.InvalidTokenError as e:
        print(f"Invalid token: {e}")
        return None
    except Exception as e:
        print(f"Token verification error: {e}")
        return None


async def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> Optional[AuthUser]:
    """
    Optional dependency to get the current authenticated user.
    Returns None if not authenticated (for mixed public/protected endpoints).
    """
    if not credentials:
        return None

    user = await verify_token(credentials.credentials)
    return user


async def require_auth(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> AuthUser:
    """
    Required dependency that ensures user is authenticated.
    Raises 401 Unauthorized if no valid token is provided.
    """
    if not credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required",
            headers={"WWW-Authenticate": "Bearer"},
        )

    user = await verify_token(credentials.credentials)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired session",
            headers={"WWW-Authenticate": "Bearer"},
        )

    return user
